### PR TITLE
chore(Pagination): add tests

### PR DESCRIPTION
**Pull request by GermanVor**

### CODE REVIEW

**Comment by jhoncool** [comment]
@GermanVor what a problem are you trying to solve here? 
total === undefined it's valid case when you can get next page

**Comment by GermanVor** [comment]
@jhoncool 

https://t.me/gravity_ui_chat/1624

**Comment by jhoncool** [comment]
> @jhoncool
> 
> https://t.me/gravity_ui_chat/1624

It's not a bug. It's by design

**Comment by GermanVor** [comment]
@jhoncool [1f68b21](https://github.com/gravity-ui/uikit/pull/1605/commits/1f68b21ad81a753e9988ed55b6b489acc5010ac9)

Change PR name

**Review by jhoncool — APPROVED** [review]

**Pull request merged**
