### PR TITLE
feat(ClipboardButton): add children and iconPosition

### PR DESCRIPTION
**Pull request by kvestus**

### CODE REVIEW

**Comment by Raubzeug** [comment]
Please add tests for your case.

**Comment by kvestus** [comment]
> Please add tests for your case.

Added test for my case and visual tests for all stories

**Comment by Raubzeug** [comment]
Visual test will be added in #1777 , so no need in it in this PR

**Comment by kvestus** [comment]
@Raubzeug ready

**Review by Raubzeug — APPROVED** [review]

**Pull request merged**
