### PR TITLE
feat(Pagination): add size prop

### LINKED ISSUE #1653: Support `size` in `Pagination`

### PR DESCRIPTION
**Pull request by spotikhanov**
This change resolves #1653 by adding 'size' prop to Pagination component with backward compatibility.

### CODE REVIEW

**Comment by jhoncool** [comment]
@spotikhanov I think in the original issue user wanted to use another types of sizes. We can support `s` and `xl` cuz select, input and button support these sizes too.

**Comment by spotikhanov** [comment]
> @spotikhanov I think in the original issue user wanted to use another types of sizes. We can support `s` and `xl` cuz select, input and button support these sizes too.

Oh, if so, I can add 's' and 'xl' to the possible PaginationSize values and make sure everything works as expected

I've added tests just to make sure that adding 'size' will not cause pagination to change for users without this prop

**Comment by spotikhanov** [comment]
@jhoncool added support for 's' and 'xl' variants. not really sure about the exact padding values in the following files:
- PaginationEllipsis.scss
- PaginationInput.scss
- PaginationPage.scss
- PaginationPageOf.scss

**Comment by jhoncool** [comment]
> @jhoncool added support for 's' and 'xl' variants. not really sure about the exact padding values in the following files:
> 
> * PaginationEllipsis.scss
> * PaginationInput.scss
> * PaginationPage.scss
> * PaginationPageOf.scss

awesome 🤗

**Review by jhoncool — APPROVED** [review]

**Comment by spotikhanov** [comment]
@jhoncool Hi! Can we merge it? What's the workflow in Gravity UI, who can get a write access?

**Comment by jhoncool** [comment]
> @jhoncool Hi! Can we merge it? What's the workflow in Gravity UI, who can get a write access?

I don't know 🤷‍♂️. I think you can do itю

**Pull request merged**
