### PR TITLE
chore(Link)!: "href" property is required

### PR DESCRIPTION
**Pull request by LakeVostok**
UXRFC-1

### CODE REVIEW

**Review by vrozaev — APPROVED** [review]

**Comment by amje** [comment]
@LakeVostok Let's rebase this PR into `next` branch.

**Comment by LakeVostok** [comment]
> @LakeVostok Let's rebase this PR into `next` branch.

done

**Comment by amje** [comment]
@LakeVostok Looks like there are still commits from old next

**Comment by LakeVostok** [comment]
@kseniya57 @ValeraS @korvin89

**Comment by amje** [comment]
> @kseniya57 @ValeraS @korvin89

@LakeVostok We decided to delay this feature until next major release due to internal use cases where href absence is legit.

**Comment by amje** [comment]
@LakeVostok I've created a new next branch for v6 release. Let's merge this PR into it

**Pull request closed without merging**
