### PR TITLE
TextInput: Add “afterClear” callback

### PR DESCRIPTION
**Pull request by Ohar**
TextInput: Add optional “afterClear” callback to invoke it after clear button handler

### CODE REVIEW

**Comment by korvin89** [comment]
Could u tell about ur use case?

**Comment by Ohar** [comment]
@korvin89 Sure!
I want to be able to do things after user clicked on the “Clear” button.
E.g. to clear my state after it.

**Comment by korvin89** [comment]
> @korvin89 Sure! I want to be able to do things after user clicked on the “Clear” button. E.g. to clear my state after it.

Why are you not satisfied with something like this:
```javascript
const onUpdate = (value) => {
    if (value === '') {
        // do some staff here
    }
};
```

**Comment by Ohar** [comment]
@korvin89 I do it now, but separated callback would let me create more clean and understadable code

**Comment by korvin89** [comment]
Okay!
1. Lets name this props `onClear`
2. Add the same props to the `TextArea`
3. Add test for this property

**Comment by Ohar** [comment]
@korvin89 Job is done, sir!
https://github.com/gravity-ui/uikit/pull/841/commits/ce3a461d371b4068efb7b8e8acee35c5e5ea921a

**Review by korvin89 — COMMENTED** [review]
Cool! Could u add description of this property to readme files?

**Comment by Ohar** [comment]
> Cool! Could u add description of this property to readme files?

[Done](https://github.com/gravity-ui/uikit/pull/841/commits/21256539960120b2e5b25d62d65449885b468d38)

**Comment by ValeraS** [comment]
@Ohar Can you provide your use case? Why is clearing input with a button different than clearing with select all + del?

**Comment by amje** [comment]
@Ohar Closing this PR, reopen if still relevant

**Pull request closed without merging**
